export const MAX_CHAT_MESSAGES = 20;
export const MAX_USER_MESSAGE_CHARACTERS = 4_000;
export const MAX_ASSISTANT_MESSAGE_CHARACTERS = 12_000;
export const MAX_CONVERSATION_CHARACTERS = 24_000;

export const REQUEST_RECENT_MESSAGE_COUNT = 6;
export const REQUEST_ASSISTANT_EXCERPT_CHARACTERS = 2_400;
export const REQUEST_MEMORY_CHARACTERS = 2_000;
export const REQUEST_CONVERSATION_CHARACTERS = 9_000;
